.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GOO" "1" "September 2016" "" ""
.
.SH "NAME"
\fBgoo\fR \- Search Stack Overflow & Wikipedia from the command line
.
.SH "SYNOPSIS"
\fBgoo\fR [\fImore\fR] [\fIexpand\fR]
.
.SH "DESCRIPTION"
Goo is a command line utility for searching the web\. Goo currently uses Stack Overflow, Wikipedia, and Drupal as resources for searching\.
.
.SH "OPTIONS"
.
.TP
\fBmore\fR
For Stack Overflow, will display the next answer on the page For Wikipedia, will display the next paragraph on the page
.
.TP
\fBexpand\fR
Expands a truncated result display
.
.SH "EXAMPLES"
\fIForthcoming\fR
.
.SH "COPYRIGHT"
Goo is copyright (c) 2016, Alex Banks, Matt Borowiec, Angela Riggs, Toby Craig, Michelle Udem\. Released under the MIT license\.
.
.SH "AUTHOR"
This man page was authored by (Angela Riggs)[https://github\.com/angelariggs]
