.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GOOPAL" "1" "September 2016" "" ""
.
.SH "NAME"
\fBGoopal\fR \- Search Stack Overflow, Wikipedia, & Drupal from the command line
.
.SH "SYNOPSIS"
\fBgoopal\fR [more] [again]
.
.SH "DESCRIPTION"
\fIGoopal\fR is a command line utility for searching the web\. Goopal currently uses Stack Overflow, Wikipedia, and Drupal as resources for searching\.
.
.SH "OPTIONS"
.
.TP
\fBmore\fR
For Stack Overflow, this will display the next answer on the page\. For Wikipedia, this will display the next paragraph / chunk on the page
.
.TP
\fBagain\fR
Displays the results of your most recent query
.
.SH "COPYRIGHT"
Goopal is copyright (c) 2016, Alex Banks, Matt Borowiec, Angela Riggs, Toby Craig, Michelle Udem\. Released under the MIT license\.
.
.SH "AUTHOR"
This man page was authored by Angela Riggs \fIhttps://github\.com/angelariggs\fR
